### ISSUE TITLE
Problema downloader

### ISSUE THREAD

**Issue by LeiX-21** [Tecnologica-Mente/myZanichelli_DRM_Remover#1]
Buonasera, ho un problema sia con il downloader kitaboo che con quello booktab.
Lo script per booktab va in errore dopo il login avvenuto correttamente:
![image](https://github.com/Tecnologica-Mente/myZanichelli_DRM_Remover/assets/67823089/cb290f45-90c4-434e-8f94-2a4863489c7e)
Mentre lo script kitaboo mentre estrae le pagine dà l'errore:
![image](https://github.com/Tecnologica-Mente/myZanichelli_DRM_Remover/assets/67823089/b2b1e95a-0a26-494c-a3ee-67bc3b5f826e)

**Comment by Tecnologica-Mente** [comment]
Buonasera e grazie per la segnalazione.

Per quanto riguarda il secondo problema (script Kitaboo), avevo già notato che con alcuni libri lo faceva, probabilmente perché non riesce per qualche motivo a puntare al link preciso della pagina e quindi la salta (di conseguenza il PDF risulta tutto bianco).

Per quanto riguarda invece il primo (login con Booktab), ho provato a loggarmi e in effetti è come ha segnalato. Probabilmente Zanichelli è corso ai ripari: ora lo script va in errore anche se ci si logga correttamente in Booktab! Restituisce un errore di certificato.

Mi sa tanto che andrà aggiornato tutto lo script! Appena avrò un po' di tempo cercherò di risolverlo, ma deve avere un po' di pazienza. Saluti.

**Comment by Tecnologica-Mente** [comment]
Script aggiornato e problema risolto!
