### ISSUE TITLE
Problema con booktab downloader

### ISSUE THREAD

**Issue by mohaashraf11** [Tecnologica-Mente/myZanichelli_DRM_Remover#2]
Buonasera, ho un problema con il download da booktab e mi appare questo messaggio.
Grazie in anticipo.

![1](https://github.com/Tecnologica-Mente/myZanichelli_DRM_Remover/assets/146657997/92a5a715-4627-406d-bd4e-6475efed8ef3)

**Comment by Tecnologica-Mente** [comment]
Strano che lo faccia. Ho verificato e a me non lo dice...
Comunque il problema è facilmente risolvibile. Nel terminale di Python basta digitare il seguente comando:
pip install requests
Efettui la stessa operazione nel caso le segnali l'assenza di altri moduli. In altre parole basta digitare sempre:
pip install <nome_modulo_mancante>
dove al posto di <nome_modulo_mancante> deve inserire il nome dell'eventuale modulo mancante.
Saluti.
