### ISSUE TITLE
Problema con download_booktab

### ISSUE THREAD

**Issue by LASTDREAMERORIGINAL** [Tecnologica-Mente/myZanichelli_DRM_Remover#4]
Dopo aver fatto correttamente il log-in e inserito il codice del libro mi dà questo errore 
![download_booktab_error](https://github.com/Tecnologica-Mente/myZanichelli_DRM_Remover/assets/147058595/561ee24f-2314-4e92-b775-380f06f392bf)
Nel caso ci mancasse qualcosa nella mia procedura questo è la mia cartella myZanichelli_DRM_Remover-main 
![myZanichelli_DRM_Remover-main](https://github.com/Tecnologica-Mente/myZanichelli_DRM_Remover/assets/147058595/482760eb-3a65-4d10-8c9f-6b4eea670e94)

**Comment by Tecnologica-Mente** [comment]
Ciao. Ho appena riprovato la procedura con il mio account e non mi da' nessun problema. Forse l'errore è dovuto al libro, magari non si può scaricare (può succedere). Hai avuto modo di provare con qualche altro libro?

**Comment by LASTDREAMERORIGINAL** [comment]
> Ciao. Ho appena riprovato la procedura con il mio account e non mi da' nessun problema. Forse l'errore è dovuto al libro, magari non si può scaricare (può succedere). Hai avuto modo di provare con qualche altro libro?

Si hai ragione, provando con un altro libro il problema non sussiste
