### ISSUE TITLE
Python updater doesn't automatically start

### ISSUE THREAD

**Issue by YosypC** [Tecnologica-Mente/myZanichelli_DRM_Remover#5]
I inadvertently hit the right mouse button on the newly created console (after selecting 3 on the main menu) to paste the pip clipboard content: the program doesn't do it by itself.
Also the same thing happens again after the download.

**Comment by Tecnologica-Mente** [comment]
The right-click Paste option only works on the Console Launcher which opens automatically after pressing button 3. If it doesn't work, you probably haven't given permission for the App to access the contents of the Windows Clipboard. Try again
